Array.prototype.del=function(h){h.sort();for(var q=this.concat([]),b=h.length-1;0<=b;b--)q=q.slice(0,h[b]).concat(q.slice(h[b]+1));return q};HTMLImageElement.prototype.loadOnce=function(h){var q=0;this.onload=function(){q||h.call(this,null);q++}};
(function(h){var q={lib:[],init:function(){this.require("config")},module:function(b,a){this.lib[b]=a.call(null,this)},require:function(b){var a=this,c=document.createElement("script");document.body.appendChild(c);c.src="./js/module/"+b+".js";c.onload=c.onerror=function(c){a.handlerror(c)}},handlerror:function(){},destroySelf:function(b){delete window[h];throw Error(b);},reflect:function(b,a,c){b=this.lib.config.getModuleName(b);return this.lib[b].process(a,c)},reflectEasy:function(b){b=this.lib.config.getEasyFun(b);
return this.lib.easy.getFun(b)},add:function(b,a,c,d,e,k,j,f){return this.lib.addLayer.add(b,a,c,d,e,k,j,f)},applyMatrix:function(){}};window[h]=function(b,a,c){if(this instanceof window[h]){this.startTime=+new Date;var d=document.createElement("canvas"),e=d.getContext("2d");isNaN(b)?(d.width=parseInt(b.width),d.height=parseInt(b.height),a=getComputedStyle(b),imgWidth=parseInt(a.getPropertyValue("width")),imgHeight=parseInt(a.getPropertyValue("height")),isNaN(imgWidth)?e.drawImage(b,0,0):e.drawImage(b,
0,0,imgWidth,imgHeight)):(d.width=b,d.height=a,e.fillStyle=c||"rgba(255,1,1,0)",e.fillRect(0,0,b,a));this.canvas=d;this.context=e;this.imgData=e.getImageData(0,0,d.width,d.height);this.name=h+"_"+Math.random();this.canvas.id=this.name;this.layers=[]}else return new window[h](b,a,c)};window[h].module=function(b,a){q.module(b,a)};window[h].dorsyMath=function(){return q.lib.dorsyMath};window[h].prototype={act:function(b,a){for(var c=[],d=0;d<arguments.length;d++)0!=d&&c.push(arguments[d]);q.reflect(b,
this.imgData,c);return this},view:function(b,a,c,d,e){var k=this.clone();k.type=1;this.addLayer(k,"\u6b63\u5e38",0,0);k.act(b,a,c,d,e);return this},excute:function(){var b=this.layers,a=b.length;b[a-1]&&1==b[a-1][0].type&&(this.imgData=b[a-1][0].imgData,delete b[a-1])},cancel:function(){var b=this.layers,a=b.length;b[a-1]&&1==b[a-1][0].type&&delete b[a-1]},show:function(b,a){var c=new window[h](this.canvas.width,this.canvas.height);c.add(this,"\u6b63\u5e38",0,0,a);this.tempPsLib=c;for(var d=0;d<this.layers.length;d++){var e=
this.layers[d],k=e[0].layers,j=e[0];k[k.length-1]&&1==k[k.length-1][0].type&&(j=k[k.length-1][0]);c.add(j,e[1],e[2],e[3],a)}this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.context.putImageData(c.imgData,0,0);b?document.querySelector(b).appendChild(this.canvas):document.body.appendChild(this.canvas);return this},replace:function(b){b&&(b.onload=function(){},b.src=this.save());return this},add:function(){var b=[],a,c,d,e,k;for(d=0;d<arguments.length;d++)if(d)switch(typeof arguments[d]){case "string":/\d+%/.test(arguments[d])?
c=arguments[d].replace("%",""):/[RGB]+/.test(arguments[d])?k=arguments[d]:a=arguments[d];break;case "number":b.push(arguments[d]);break;case "boolean":e=arguments[d]}d=b[0]||0;b=b[1]||0;this.imgData=q.add(this.imgData,arguments[0].imgData,a||"\u6b63\u5e38",c/100||1,d,b,e||!1,k||"RGB");return this},addLayer:function(b,a,c,d){this.layers.push([b,a,c,d]);return this},clone:function(){var b=new window[h](this.canvas.width,this.canvas.height);b.context.putImageData(this.imgData,0,0);b.imgData=b.context.getImageData(0,
0,this.canvas.width,this.canvas.height);return b},swap:function(b,a){var c=this.layers[b];this.layers[b]=this.layers[a];this.layers[a]=c;return this},deleteLayers:function(b){this.layers=this.layers.del(b)},save:function(b){if(!this.layers.length)return this.context.putImageData(this.imgData,0,0),this.canvas.toDataURL();var a=new window[h](this.canvas.width,this.canvas.height);a.add(this,"\u6b63\u5e38",0,0,b);this.tempPsLib=a;for(var c=0;c<this.layers.length;c++){var d=this.layers[c],e=d[0].layers,
k=d[0];e[e.length-1]&&1==e[e.length-1][0].type&&(k=e[e.length-1][0]);a.add(k,d[1],d[2],d[3],b)}this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.context.putImageData(a.imgData,0,0);return this.canvas.toDataURL()},drawRect:function(){var b;if(!(b=document.getElementById("imgRect")))b=document.createElement("canvas"),b.id="imgRect",document.body.appendChild(b),b.width=parseInt(this.canvas.width),b.height=parseInt(this.canvas.height);var a=b.getContext("2d");a.clearRect(0,0,b.width,
b.height);for(var c=[],d=this.tempPsLib.imgData.data,e=0,k=d.length;e<k;e++)c[d[e]]?c[d[e]]++:c[d[e]]=1;a.beginPath();a.moveTo(0,b.height);for(e=d=0;255>e;e++)c[e]>d&&(d=c[e]);for(e=0;255>e;e++)k=c[e]||0,k=b.height-0.8*(k/d)*b.height,a.lineTo(e/256*b.width,k,1,1);a.lineTo(b.width+10,b.height);a.fill()},ps:function(b){var a;a=q.reflectEasy(b).call(this);this.logTime("\u7ec4\u5408\u6548\u679c"+b);return a},logTime:function(b){console.log(b+": "+(+new Date-this.startTime)/1E3+"s")}}})("psLib");
window.AlloyImage=$AI=window.psLib;(function(h){window[h].module("ImageEnhance",function(){return{process:function(q){for(var b=q.data,a=0,c=b.length;a<c;a+=4);q.data=b;return q}}})})("psLib");
(function(h){window[h].module("addLayer",function(){return{add:function(q,b,a,c,d,e,k,j){var f=q.data,m=b.data;d=d||0;e=e||0;c=c||1;k=k||!1;j=j||"RGB";/[RGB]+/.test(j)||(j="RGB");var p=j.replace("R","0").replace("G","1").replace("B","2"),h=1;k&&(h=1);var n;k=q.width;j=m.length;b=b.width;for(var p=[-1<p.indexOf("0"),-1<p.indexOf("1"),-1<p.indexOf("2")],h=4*h,l=0,s=f.length;l<s;l+=h){var g=l/4,r=parseInt(g/k),g=g%k-d,r=4*((r-e)*b+g);if(0<=r&&r<j-4&&g<b&&0<=g)for(g=0;3>g&&0!=m[r+3];g++)switch(f[l+3]=
m[r+3],a){case "\u989c\u8272\u51cf\u6de1":p[g]&&(n=f[l+g]+f[l+g]*m[r+g]/(255-m[r+g]),f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u53d8\u6697":p[g]&&(n=f[l+g]<m[r+g]?f[l+g]:m[r+g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u53d8\u4eae":p[g]&&(n=f[l+g]>m[r+g]?f[l+g]:m[r+g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u6b63\u7247\u53e0\u5e95":p[g]&&(n=parseInt(f[l+g]*m[r+g]/255),f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u6ee4\u8272":p[g]&&(n=parseInt(255-(255-f[l+g])*(255-m[r+g])/255),f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u53e0\u52a0":p[g]&&
(n=127.5>=f[l+g]?f[l+g]*m[r+g]/127.5:255-(255-f[l+g])*(255-m[r+g])/127.5,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u5f3a\u5149":p[g]&&(n=127.5>=m[r+g]?f[l+g]*m[r+g]/127.5:f[l+g]+(255-f[l+g])*(m[r+g]-127.5)/127.5,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u5dee\u503c":p[g]&&(n=f[l+g]>m[r+g]?f[l+g]-m[r+g]:m[r+g]-f[l+g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u6392\u9664":p[g]&&(n=f[l+g]+m[r+g]-f[l+g]*m[r+g]/127.5,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u70b9\u5149":p[g]&&(n=f[l+g]<2*m[r+g]-255?2*m[r+g]-255:f[l+
g]<2*m[r+g]?f[l+g]:2*m[r+g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u989c\u8272\u52a0\u6df1":p[g]&&(n=255-255*(255-f[l+g])/m[r+g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u7ebf\u6027\u52a0\u6df1":p[g]&&(n=f[l+g]+m[r+g],n=255<n?n-255:0,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u7ebf\u6027\u51cf\u6de1":p[g]&&(n=f[l+g]+m[r+g],n=255<n?255:n,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u67d4\u5149":p[g]&&(n=127.5>m[r+g]?((2*m[r+g]-255)*(255-f[l+g])/65025+1)*f[l+g]:(2*m[r+g]-255)*(Math.sqrt(f[l+g]/255)-f[l+g]/255)+f[l+
g],f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u4eae\u5149":p[g]&&(n=127.5>m[r+g]?255*(1-(255-f[l+g])/(2*m[r+g])):f[l+g]/(2*(1-m[r+g]/255)),f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u7ebf\u6027\u5149":p[g]&&(n=f[l+g]+2*m[r+g]-255,n=255<n?255:n,f[l+g]=(1-c)*f[l+g]+c*n);break;case "\u5b9e\u8272\u6df7\u5408":p[g]&&(n=m[r+g]<255-f[l+g]?0:255,f[l+g]=(1-c)*f[l+g]+c*n);break;default:p[g]&&(n=m[r+g],f[l+g]=(1-c)*f[l+g]+c*n)}}q.data=f;return q}}})})("psLib");
(function(h){window[h].module("alterRGB",function(){return{process:function(q,b){for(var a=q.data,c=b[0]/50,d=Math.tan((45+44*((b[1]||0)/50))*Math.PI/180),e=0,k=a.length;e<k;e+=4)for(var j=0;3>j;j++)a[e+j]=(a[e+j]-127.5*(1-c))*d+127.5*(1+c);q.data=a;return q}}})})("psLib");
(function(h){window[h].module("applyMatrix",function(q){return{process:function(b){for(var a=b.data,c=b.width,d=new q.lib.dorsyMath.Matrix([-2,-4,-4,-4,-2,-4,0,8,0,-4,-4,8,24,8,-4,-4,0,8,0,-4,-2,-4,-4,-4,-2],25,1),e=[],k=0,j=a.length;k<j;k+=4){var f=k/4,m=parseInt(f/c),p=f%c;if(!(0==m||0==p)){for(var h=[[],[],[]],n=-2;3>n;n++)for(var l=m+n,s=-2;3>s;s++)for(var g=4*(l*c+(p+s)),f=0;3>f;f++)h[f].push(a[g+f]);m=(new q.lib.dorsyMath.Matrix(h,3,matrixSize)).mutiply(d);for(f=0;3>f;f++)e[k+f]=m.data[f];e[k+
4]=a[k+4]}}k=0;for(j=a.length;k<j;k++)a[k]=e[k]||a[k];return b}}})})("psLib");
(function(h){window[h].module("config",function(){var q={"\u7070\u5ea6\u5904\u7406":"toGray","\u53cd\u8272":"toReverse","\u7070\u5ea6\u9608\u503c":"toThresh","\u9ad8\u65af\u6a21\u7cca":"gaussBlur","\u4eae\u5ea6":"alterRGB","\u6d6e\u96d5\u6548\u679c":"embossment","\u67e5\u627e\u8fb9\u7f18":"lapOfGauss","\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282":"setHSI","\u9a6c\u8d5b\u514b":"mosaic","\u6cb9\u753b":"oilPainting","\u8150\u8680":"corrode","\u9510\u5316":"sharp","\u6dfb\u52a0\u6742\u8272":"noise","\u66f2\u7ebf":"curve",
"\u6697\u89d2":"darkCorner","\u55b7\u70b9":"dotted"},b={"\u7f8e\u80a4":"e1","\u7d20\u63cf":"e2","\u81ea\u7136\u589e\u5f3a":"e3","\u7d2b\u8c03":"e4","\u67d4\u7126":"e5","\u590d\u53e4":"e6","\u9ed1\u767d":"e7","\u4efflomo":"e8","\u4eae\u767d\u589e\u5f3a":"e9","\u7070\u767d":"e10","\u7070\u8272":"e11","\u6696\u79cb":"e12","\u6728\u96d5":"e13","\u7c97\u7cd9":"e14"};return{getModuleName:function(a){return q[a]||a},getEasyFun:function(a){return b[a]||a}}})})("psLib");
(function(h){window[h].module("corrode",function(){return{process:function(q,b){for(var a=parseInt(b[0])||3,c=q.data,d=q.width,e=q.height,k=0;k<d;k++)for(var j=0;j<e;j++)for(var f=parseInt(2*Math.random()*a)-a,m=parseInt(2*Math.random()*a)-a,p=j*d+k,f=(j+f)*d+k+m,m=0;3>m;m++)c[4*p+m]=c[4*f+m];return q}}})})("psLib");
(function(h){window[h].module("curve",function(q){return{process:function(b,a){for(var c=q.lib.dorsyMath.lagrange(a[0],a[1]),d=b.data,e=b.width,k=b.height,j=0;j<e;j++)for(var f=0;f<k;f++)for(var m=f*e+j,p=0;3>p;p++)d[4*m+p]=c(d[4*m+p]);return b}}})})("psLib");
(function(h){window[h].module("darkCorner",function(q){return{process:function(b,a){for(var c=parseInt(a[0])||3,d=a[1]||30,e=b.data,k=b.width,j=b.height,f=2*k/3,m=1*j/2,p=q.lib.dorsyMath.distance([f,m]),c=p*(1-c/10),h=0;h<k;h++)for(var n=0;n<j;n++)for(var l=n*k+h,s=0;3>s;s++){var g;g=e[4*l+s];var r=(q.lib.dorsyMath.distance([h,n],[f,m])-c)/(p-c);0>r&&(r=0);g=(0*Math.pow(1-r,3)+0.06*r*Math.pow(1-r,2)+3*0.3*r*r*(1-r)+1*Math.pow(r,3))*g*d/255;e[4*l+s]-=g}return b}}})})("psLib");
(function(h){window[h].module("dorsyMath",function(q){var b={FFT1:function(a){function c(){e++;for(var f=d/Math.pow(2,e),j=d/f,p=0;p<f;p++)for(var q=p*j,n=(p+1)*j-1,l=e,h=Math.pow(2,l-1),g=0;q<=n-h;q++){var r=q+h,v=g*d/Math.pow(2,l),u=v+d/4;a[q]instanceof b.C||(a[q]=new b.C(a[q]));a[r]instanceof b.C||(a[r]=new b.C(a[r]));v=a[q].plus(a[r].mutiply(k[v]));u=a[q].plus(a[r].mutiply(k[u]));a[q]=v;a[r]=u;g++}1<f&&c()}for(var d=a.length,e=0,k=[],j=0;j<d;j++)k[j]=this.exp(-2*Math.PI*j/d);c();return a},DFT:function(){},
Matrix:function(a,c,b){var e=[];if(c){if(isNaN(c)){var k=/(\d+)\*/.exec(c)[1];c=/\*(\d+)/.exec(c)[1]}else k=c,c=b;if(a[0]&&a[0][0])for(b=0;b<k;b++){e[b]=[];for(var j=0;j<c;j++)e[b][j]=a[b][j]||0}else for(b=0;b<k;b++){e[b]=[];for(j=0;j<c;j++)e[b][j]=a[b*c+j]||0}this.m=k;this.n=c}else this.m=a.length,this.n=a[0].length;this.data=e},C:function(a,c){this.r=a||0;this.i=c||0},exp:function(a,c){a=a||0;c=c||1;var d=new b.C;d.r=c*Math.cos(a);d.i=c*Math.sin(a);return d},lagrange:function(a,c){var b=a.length;
return function(e){for(var k=0,j=0;j<b;j++){for(var f=1,m=1,q=0;q<b;q++)q!=j&&(f*=a[j]-a[q],m*=e-a[q]);k+=c[j]*(m/f)}return k}},applyMatrix:function(a,c,d){d=d||0;var e=a.data,k=a.width,j=c.length;c=new b.Matrix(c,j,1);for(var f=[],m=-(Math.sqrt(j)-1)/2,p=0,h=e.length;p<h;p+=4){var n=p/4,l=parseInt(n/k),s=n%k;if(!(0==l||0==s)){for(var g=[[],[],[]],r=m;r<=-m;r++)for(var v=l+r,u=m;u<=-m;u++)for(var w=4*(v*k+(s+u)),n=0;3>n;n++)g[n].push(e[w+n]);l=(new q.lib.dorsyMath.Matrix(g,3,j)).mutiply(c);for(n=
0;3>n;n++)f[p+n]=l.data[n];f[p+4]=e[p+4]}}p=0;for(h=e.length;p<h;p++)f[p]&&(e[p]=f[p]<d?f[p]:e[p]);return a},RGBToHSI:function(a,c,b){var e=(a-c+a-b)/2/Math.sqrt((a-c)*(a-c)+(a-b)*(c-b))||0,e=Math.acos(e),e=b>c?2*Math.PI-e:e,k=1-3*Math.min(a,c,b)/(a+c+b);e>2*Math.PI&&(e=2*Math.PI);0>e&&(e=0);return{H:e,S:k,I:(a+c+b)/3}},HSIToRGB:function(a,c,b){0>a?(a%=2*Math.PI,a+=2*Math.PI):a%=2*Math.PI;if(a<=2*Math.PI/3)var e=b*(1-c),k=b*(1+c*Math.cos(a)/Math.cos(Math.PI/3-a)),j=3*b-(k+e);else a<=4*Math.PI/3?(a-=
2*Math.PI/3,k=b*(1-c),j=b*(1+c*Math.cos(a)/Math.cos(Math.PI/3-a)),e=3*b-(j+k)):(a-=4*Math.PI/3,j=b*(1-c),e=b*(1+c*Math.cos(a)/Math.cos(Math.PI/3-a)),k=3*b-(j+e));return{R:k,G:j,B:e}},applyInHSI:function(a,b){for(var d=a.data,e=0,k=d.length;e<k;e+=4){var j=this.RGBToHSI(d[e],d[e+1],d[e+2]);b(j);1<j.S&&(j.S=1);0>j.S&&(j.S=0);j=this.HSIToRGB(j.H,j.S,j.I);d[e]=j.R;d[e+1]=j.G;d[e+2]=j.B}},applyInCoordinate:function(){},distance:function(a,c){c=c||[0,0];a=new b.C(a[0],a[1]);c=new b.C(c[0],c[1]);return a.minus(c).distance()},
xyToIFun:function(a){return function(b,d,e){return 4*(d*a+b)+(e||0)}},xyCal:function(a,b,d,e,k){for(var j=this.xyToIFun(a.width),f=0;3>f;f++){var m=j(b,d,f);a[m]=e(a[m])}k&&(a[m+1]=k(a[m+1]))}};b.Matrix.prototype={plus:function(a){if(this.m!=a.m||this.n!=a.n)throw Error("\u77e9\u9635\u52a0\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,this.n),d=0;d<this.m;d++)for(var e=0;e<this.n;e++)c.data[d][e]=this.data[d][e]+a.data[d][e];return c},minus:function(a){if(this.m!=a.m||this.n!=
a.n)throw Error("\u77e9\u9635\u51cf\u6cd5\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,this.n),d=0;d<this.m;d++)for(var e=0;e<this.n;e++)c.data[d][e]=this.data[d][e]-a.data[d][e];return c},mutiply:function(a){if(this.n!=a.m)throw Error("\u77e9\u9635\u4e58\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,a.n),d=0;d<this.m;d++)for(var e=0;e<a.n;e++){for(var k=0,j=0;j<this.n;j++)k+=this.data[d][j]*a.data[j][e];c.data[d][e]=k}return c}};b.C.prototype={plus:function(a){var c=
new b.C;c.r=this.r+a.r;c.i=this.i+a.i;return c},minus:function(a){var c=new b.C;c.r=this.r-a.r;c.i=this.i-a.i;return c},mutiply:function(a){var c=new b.C;c.r=this.r*a.r-this.i*a.i;c.i=this.r*a.i+this.i*a.r;return c},divide:function(a){var c=new b.C,d=a.mutiply(a.conjugated());a=this.mutiply(a.conjugated());c.r=a.r/d.r;c.i=a.i/d.r;return c},conjugated:function(){return new b.C(this.r,-this.i)},distance:function(){return Math.sqrt(this.r*this.r+this.i*this.i)}};return b})})("psLib");
(function(h){window[h].module("dotted",function(q){return{process:function(b,a){for(var c=parseInt(a[0])||1,d=parseInt(a[1])||1,e=b.data,k=b.width,j=b.height,f=2*c+1,m=[],p=d*d,d=-c;d<c;d++)for(var h=-c;h<c;h++)d*d+h*h>p&&m.push([d,h]);c=q.lib.dorsyMath.xyToIFun(k);d=0;for(k=parseInt(k/f);d<k;d++){h=0;for(p=parseInt(j/f);h<p;h++)for(var n=parseInt((d+0.5)*f),l=parseInt((h+0.5)*f),s=0;s<m.length;s++){var g=n+m[s][0],r=l+m[s][1];e[c(g,r,3)]=225;e[c(g,r,2)]=225;e[c(g,r,0)]=225;e[c(g,r,1)]=225}}return b}}})})("psLib");
(function(h){window[h].module("easy",function(){return{getFun:function(q){return{e1:function(){return this.clone().add(this.act("\u9ad8\u65af\u6a21\u7cca",10),"\u6ee4\u8272").act("\u4eae\u5ea6",-10,5)},e2:function(){var b=this.act("\u7070\u5ea6\u5904\u7406").clone();return this.add(b.act("\u53cd\u8272").act("\u9ad8\u65af\u6a21\u7cca",8),"\u989c\u8272\u51cf\u6de1").act("\u9510\u5316",1)},e3:function(){return this.act("\u66f2\u7ebf",[0,190,255],[0,229,255])},e4:function(){var b=this.clone();return this.add(b.act("\u9ad8\u65af\u6a21\u7cca",
3),"\u6b63\u7247\u53e0\u5e95","RG")},e5:function(){var b=this.clone();return this.add(b.act("\u9ad8\u65af\u6a21\u7cca",6),"\u53d8\u6697")},e6:function(){this.clone();return this.act("\u7070\u5ea6\u5904\u7406").add(window[h](this.canvas.width,this.canvas.height,"#808080").act("\u6dfb\u52a0\u6742\u8272").act("\u9ad8\u65af\u6a21\u7cca",4).act("\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282",32,19,0,!0),"\u53e0\u52a0")},e7:function(){return this.act("\u7070\u5ea6\u5904\u7406")},e8:function(){return this.clone().add(this.clone(),
"\u6ee4\u8272").add(this.clone(),"\u67d4\u5149").add(this.clone().act("\u53cd\u8272"),"\u6b63\u5e38","20%","B").act("\u6697\u89d2",6,200)},e9:function(){return this.clone().add(this.clone().act("\u66f2\u7ebf",[0,50,255],[0,234,255]),"\u67d4\u5149")},e10:function(){return this.act("\u7070\u5ea6\u5904\u7406").act("\u66f2\u7ebf",[0,61,69,212,255],[0,111,176,237,255])},e11:function(){return this.act("\u7070\u5ea6\u5904\u7406").act("\u66f2\u7ebf",[0,60,142,194,255],[0,194,240,247,255])},e12:function(){var b=
this.clone().act("\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282",36,47,8,!0).act("\u6697\u89d2",6,150);return this.add(b,"\u53e0\u52a0")},e13:function(){var b=this.clone().act("\u9a6c\u8d5b\u514b").act("\u67e5\u627e\u8fb9\u7f18").act("\u6d6e\u96d5\u6548\u679c");return this.add(b,"\u7ebf\u6027\u5149")},e14:function(){return this.add(window[h](this.canvas.width,this.canvas.height,"#000").act("\u55b7\u70b9").act("\u6d6e\u96d5\u6548\u679c"),"\u53e0\u52a0")}}[q]}}})})("psLib");
(function(h){window[h].module("embossment",function(){return{process:function(q){for(var b=q.data,a=q.width,c=[],d=0,e=b.length;d<e;d+=4){var k=d/4,j=parseInt(k/a),f=k%a,k=4*((j-1)*a+(f-1)),m=4*(j+1)*a+4*(f+1);if(!(0==j||0==f)){for(j=0;3>j;j++)c[d+j]=b[k+j]-b[m+j]+127.5;c[d+4]=b[d+4]}}d=0;for(e=b.length;d<e;d++)b[d]=c[d]||b[d];return q}}})})("psLib");
(function(h){window[h].module("gaussBlur",function(){return{process:function(q,b,a){var c=q.data,d=q.width,e=q.height,k=[],j=0,f,m,h,t,n,l;b=Math.floor(b)||3;a=a||b/3;f=1/(Math.sqrt(2*Math.PI)*a);t=-1/(2*a*a);n=0;for(a=-b;a<=b;a++,n++)h=f*Math.exp(t*a*a),k[n]=h,j+=h;n=0;for(a=k.length;n<a;n++)k[n]/=j;for(f=0;f<e;f++)for(a=0;a<d;a++){j=m=h=t=0;for(l=-b;l<=b;l++)n=a+l,0<=n&&n<d&&(n=4*(f*d+n),m+=c[n]*k[l+b],h+=c[n+1]*k[l+b],t+=c[n+2]*k[l+b],j+=k[l+b]);n=4*(f*d+a);c[n]=m/j;c[n+1]=h/j;c[n+2]=t/j}for(a=
0;a<d;a++)for(f=0;f<e;f++){j=m=h=t=0;for(l=-b;l<=b;l++)n=f+l,0<=n&&n<e&&(n=4*(n*d+a),m+=c[n]*k[l+b],h+=c[n+1]*k[l+b],t+=c[n+2]*k[l+b],j+=k[l+b]);n=4*(f*d+a);c[n]=m/j;c[n+1]=h/j;c[n+2]=t/j}q.data=c;return q}}})})("psLib");(function(h){window[h].module("lapOfGauss",function(h){return{process:function(b){return h.lib.dorsyMath.applyMatrix(b,[0,1,0,1,-4,1,0,1,0],250)}}})})("psLib");
(function(h){window[h].module("mosaic",function(){return{process:function(h,b){for(var a=parseInt(b[0])||3,c=h.data,d=h.width,e=h.height,a=2*a+1,k=0,j=parseInt(d/a);k<j;k++)for(var f=0,m=parseInt(e/a);f<m;f++){for(var p=[],t=[0,0,0],n=0;n<a;n++)for(var l=0;l<a;l++){var s=(f*a+n)*d+k*a+l;t[0]+=c[4*s];t[1]+=c[4*s+1];t[2]+=c[4*s+2]}p[0]=t[0]/(a*a);p[1]=t[1]/(a*a);p[2]=t[2]/(a*a);for(n=0;n<a;n++)for(l=0;l<a;l++)s=(f*a+n)*d+k*a+l,c[4*s]=p[0],c[4*s+1]=p[1],c[4*s+2]=p[2]}return h}}})})("psLib");
(function(h){window[h].module("noise",function(){return{process:function(h,b){for(var a=parseInt(b[0])||100,c=h.data,d=h.width,e=h.height,k=0;k<d;k++)for(var j=0;j<e;j++)for(var f=j*d+k,m=0;3>m;m++){var p=parseInt(2*Math.random()*a)-a;c[4*f+m]+=p}return h}}})})("psLib");
(function(h){window[h].module("oilPainting",function(){return{process:function(h,b){for(var a=parseInt(b[0])||16,c=h.data,d=h.width,e=h.height,k=0;k<d;k++)for(var j=0;j<e;j++){for(var f=j*d+k,m=0,p=0;3>p;p++)m+=c[4*f+p];m/=3;m=parseInt(m/a)*a;for(p=0;3>p;p++)c[4*f+p]=m}return h}}})})("psLib");
(function(h){window[h].module("setHSI",function(h){return{process:function(b,a){a[0]=a[0]/180*Math.PI;a[1]=a[1]/100||0;a[2]=255*(a[2]/100)||0;a[3]=a[3]||!1;h.lib.dorsyMath.applyInHSI(b,function(b){a[3]?(b.H=a[0],b.S=a[1]):(b.H+=a[0],b.S+=a[1]);b.I+=a[2]});return b}}})})("psLib");
(function(h){window[h].module("sharp",function(){return{process:function(h,b){for(var a=b[0]||0.6,c=h.data,d=h.width,e=0,k=c.length;e<k;e+=4){var j=e/4,f=parseInt(j/d),m=j%d;if(!(0==f||0==m))for(var p=4*((f-1)*d+(m-1)),f=4*((f-1)*d+m),j=4*(j-1),m=0;3>m;m++)c[e+m]+=(c[e+m]-(c[f+m]+c[j+m]+c[p+m])/3)*a}return h}}})})("psLib");
(function(h){window[h].module("toGray",function(){return{process:function(h){for(var b=h.data,a=0,c=b.length;a<c;a+=4){var d=parseInt((b[a]+b[a+1]+b[a+2])/3);b[a+2]=b[a+1]=b[a]=d}h.data=b;return h}}})})("psLib");(function(h){window[h].module("toReverse",function(){return{process:function(h){for(var b=h.data,a=0,c=b.length;a<c;a+=4)b[a]=255-b[a],b[a+1]=255-b[a+1],b[a+2]=255-b[a+2];h.data=b;return h}}})})("psLib");
(function(h){window[h].module("toThresh",function(h){return{process:function(b,a){b=h.lib.toGray.process(b);var c=b.data;a=a[0]||128;for(var d=0,e=c.length;d<e;d++)(d+1)%4&&(c[d]=c[d]>a?255:0);b.data=c;return b}}})})("psLib");
