Array.prototype.del=function(k){k.sort();for(var n=this.concat([]),b=k.length-1;0<=b;b--)n=n.slice(0,k[b]).concat(n.slice(k[b]+1));return n};HTMLImageElement.prototype.loadOnce=function(k){var n=0;this.onload=function(){n||k.call(this,null);n++}};
(function(k){var n={lib:[],init:function(){this.require("config")},module:function(b,a){this.lib[b]=a.call(null,this)},require:function(b){var a=this,c=document.createElement("script");document.body.appendChild(c);c.src="./js/module/"+b+".js";c.onload=c.onerror=function(c){a.handlerror(c)}},handlerror:function(){},destroySelf:function(b){delete window[k];throw Error(b);},reflect:function(b,a,c){b=this.lib.config.getModuleName(b);return this.lib[b].process(a,c)},reflectEasy:function(b){b=this.lib.config.getEasyFun(b);
return this.lib.easy.getFun(b)},add:function(b,a,c,f,g,d,j,h){return this.lib.addLayer.add(b,a,c,f,g,d,j,h)},applyMatrix:function(){}};window[k]=function(b,a,c){if(this instanceof window[k]){var f=document.createElement("canvas"),g=f.getContext("2d");isNaN(b)?(f.width=parseInt(b.width),f.height=parseInt(b.height),a=getComputedStyle(b),imgWidth=parseInt(a.getPropertyValue("width")),imgHeight=parseInt(a.getPropertyValue("height")),isNaN(imgWidth)?g.drawImage(b,0,0):g.drawImage(b,0,0,imgWidth,imgHeight)):
(f.width=b,f.height=a,g.fillStyle=c||"rgba(255,1,1,0)",g.fillRect(0,0,b,a));this.canvas=f;this.context=g;this.imgData=g.getImageData(0,0,f.width,f.height);this.name=k+"_"+Math.random();this.canvas.id=this.name;this.layers=[]}else return new window[k](b,a,c)};window[k].module=function(b,a){n.module(b,a)};window[k].dorsyMath=function(){return n.lib.dorsyMath};window[k].prototype={act:function(b,a){for(var c=[],f=0;f<arguments.length;f++)0!=f&&c.push(arguments[f]);n.reflect(b,this.imgData,c);return this},
view:function(b,a,c,f,g){var d=this.clone();d.type=1;this.addLayer(d,"\u6b63\u5e38",0,0);d.act(b,a,c,f,g);return this},excute:function(){var b=this.layers,a=b.length;b[a-1]&&1==b[a-1][0].type&&(this.imgData=b[a-1][0].imgData,delete b[a-1])},cancel:function(){var b=this.layers,a=b.length;b[a-1]&&1==b[a-1][0].type&&delete b[a-1]},show:function(b,a){var c=new window[k](this.canvas.width,this.canvas.height);c.add(this,"\u6b63\u5e38",0,0,a);this.tempPsLib=c;for(var f=0;f<this.layers.length;f++){var g=
this.layers[f],d=g[0].layers,j=g[0];d[d.length-1]&&1==d[d.length-1][0].type&&(j=d[d.length-1][0]);c.add(j,g[1],g[2],g[3],a)}this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.context.putImageData(c.imgData,0,0);b?document.querySelector(b).appendChild(this.canvas):document.body.appendChild(this.canvas);return this},replace:function(b){b&&(b.onload=function(){},b.src=this.save());return this},add:function(){var b=[],a,c,f,g,d;for(f=0;f<arguments.length;f++)if(f)switch(typeof arguments[f]){case "string":/\d+%/.test(arguments[f])?
c=arguments[f].replace("%",""):/[RGB]+/.test(arguments[f])?d=arguments[f]:a=arguments[f];break;case "number":b.push(arguments[f]);break;case "boolean":g=arguments[f]}f=b[0]||0;b=b[1]||0;this.imgData=n.add(this.imgData,arguments[0].imgData,a||"\u6b63\u5e38",c/100||1,f,b,g||!1,d||"RGB");return this},addLayer:function(b,a,c,f){this.layers.push([b,a,c,f]);return this},clone:function(){var b=new window[k](this.canvas.width,this.canvas.height);b.add(this);return b},swap:function(b,a){var c=this.layers[b];
this.layers[b]=this.layers[a];this.layers[a]=c;return this},deleteLayers:function(b){this.layers=this.layers.del(b)},save:function(b){var a=new window[k](this.canvas.width,this.canvas.height);a.add(this,"\u6b63\u5e38",0,0,b);this.tempPsLib=a;for(var c=0;c<this.layers.length;c++){var f=this.layers[c],g=f[0].layers,d=f[0];g[g.length-1]&&1==g[g.length-1][0].type&&(d=g[g.length-1][0]);a.add(d,f[1],f[2],f[3],b)}this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.context.putImageData(a.imgData,
0,0);return this.canvas.toDataURL()},drawRect:function(){var b;if(!(b=document.getElementById("imgRect")))b=document.createElement("canvas"),b.id="imgRect",document.body.appendChild(b),b.width=parseInt(this.canvas.width),b.height=parseInt(this.canvas.height);var a=b.getContext("2d");a.clearRect(0,0,b.width,b.height);for(var c=[],f=this.tempPsLib.imgData.data,g=0,d=f.length;g<d;g++)c[f[g]]?c[f[g]]++:c[f[g]]=1;a.beginPath();a.moveTo(0,b.height);for(g=f=0;255>g;g++)c[g]>f&&(f=c[g]);for(g=0;255>g;g++)d=
c[g]||0,d=b.height-0.8*(d/f)*b.height,a.lineTo(g/256*b.width,d,1,1);a.lineTo(b.width+10,height);a.fill()},ps:function(b){return b=n.reflectEasy(b).call(this)}}})("psLib");window.AlloyImage=$AI=window.psLib;(function(k){window[k].module("ImageEnhance",function(){return{process:function(n){for(var b=n.data,a=0,c=b.length;a<c;a+=4);n.data=b;return n}}})})("psLib");
(function(k){window[k].module("addLayer",function(){return{add:function(n,b,a,c,f,g,d,j){var h=n.data,l=b.data;f=f||0;g=g||0;c=c||1;d=d||!1;j=j||"RGB";/[RGB]+/.test(j)||(j="RGB");j=j.replace("R","0").replace("G","1").replace("B","2");var r=1;d&&(r=1);var m;d=0;for(var p=h.length;d<p;d+=4*r){var e=d/4;m=n.width;height=n.height;var q=parseInt(e/m),e=e%m-f,q=4*((q-g)*b.width+e);if(0<=q&&q<b.data.length-4&&e<b.width&&0<=e)for(e=0;3>e&&0!=l[q+3];e++)switch(h[d+3]=l[q+3],a){case "\u989c\u8272\u51cf\u6de1":-1<
j.indexOf(e)&&(m=h[d+e]+h[d+e]*l[q+e]/(255-l[q+e]),h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u53d8\u6697":-1<j.indexOf(e)&&(m=h[d+e]<l[q+e]?h[d+e]:l[q+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u53d8\u4eae":-1<j.indexOf(e)&&(m=h[d+e]>l[q+e]?h[d+e]:l[q+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u6b63\u7247\u53e0\u5e95":-1<j.indexOf(e)&&(m=parseInt(h[d+e]*l[q+e]/255),h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u6ee4\u8272":-1<j.indexOf(e)&&(m=parseInt(255-(255-h[d+e])*(255-l[q+e])/255),h[d+e]=(1-c)*h[d+e]+c*m);break;
case "\u53e0\u52a0":-1<j.indexOf(e)&&(m=127.5>=h[d+e]?h[d+e]*l[q+e]/127.5:255-(255-h[d+e])*(255-l[q+e])/127.5,h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u5f3a\u5149":-1<j.indexOf(e)&&(m=127.5>=l[q+e]?h[d+e]*l[q+e]/127.5:h[d+e]+(255-h[d+e])*(l[q+e]-127.5)/127.5,h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u5dee\u503c":-1<j.indexOf(e)&&(m=h[d+e]>l[q+e]?h[d+e]-l[q+e]:l[q+e]-h[d+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u6392\u9664":-1<j.indexOf(e)&&(m=h[d+e]+l[q+e]-h[d+e]*l[q+e]/127.5,h[d+e]=(1-c)*h[d+e]+c*m);break;
case "\u70b9\u5149":-1<j.indexOf(e)&&(m=h[d+e]<2*l[q+e]-255?2*l[q+e]-255:h[d+e]<2*l[q+e]?h[d+e]:2*l[q+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u989c\u8272\u52a0\u6df1":-1<j.indexOf(e)&&(m=255-255*(255-h[d+e])/l[q+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u7ebf\u6027\u52a0\u6df1":-1<j.indexOf(e)&&(m=h[d+e]+l[q+e],m=255<m?m-255:0,h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u7ebf\u6027\u51cf\u6de1":-1<j.indexOf(e)&&(m=h[d+e]+l[q+e],m=255<m?255:m,h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u67d4\u5149":-1<j.indexOf(e)&&
(m=127.5>l[q+e]?((2*l[q+e]-255)*(255-h[d+e])/65025+1)*h[d+e]:(2*l[q+e]-255)*(Math.sqrt(h[d+e]/255)-h[d+e]/255)+h[d+e],h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u4eae\u5149":-1<j.indexOf(e)&&(m=127.5>l[q+e]?255*(1-(255-h[d+e])/(2*l[q+e])):h[d+e]/(2*(1-l[q+e]/255)),h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u7ebf\u6027\u5149":-1<j.indexOf(e)&&(m=h[d+e]+2*l[q+e]-255,m=255<m?255:m,h[d+e]=(1-c)*h[d+e]+c*m);break;case "\u5b9e\u8272\u6df7\u5408":-1<j.indexOf(e)&&(m=l[q+e]<255-h[d+e]?0:255,h[d+e]=(1-c)*h[d+e]+c*m);
break;default:-1<j.indexOf(e)&&(m=l[q+e],h[d+e]=(1-c)*h[d+e]+c*m)}}n.data=h;return n}}})})("psLib");(function(k){window[k].module("alterRGB",function(){return{process:function(n,b){for(var a=n.data,c=b[0]/50,f=Math.tan((45+44*((b[1]||0)/50))*Math.PI/180),g=0,d=a.length;g<d;g+=4)for(var j=0;3>j;j++)a[g+j]=(a[g+j]-127.5*(1-c))*f+127.5*(1+c);n.data=a;return n}}})})("psLib");
(function(k){window[k].module("applyMatrix",function(n){return{process:function(b){for(var a=b.data,c=b.width,f=new n.lib.dorsyMath.Matrix([-2,-4,-4,-4,-2,-4,0,8,0,-4,-4,8,24,8,-4,-4,0,8,0,-4,-2,-4,-4,-4,-2],25,1),g=[],d=0,j=a.length;d<j;d+=4){var h=d/4,l=parseInt(h/c),r=h%c;if(!(0==l||0==r)){for(var m=[[],[],[]],p=-2;3>p;p++)for(var e=l+p,q=-2;3>q;q++)for(var k=4*(e*c+(r+q)),h=0;3>h;h++)m[h].push(a[k+h]);l=(new n.lib.dorsyMath.Matrix(m,3,matrixSize)).mutiply(f);for(h=0;3>h;h++)g[d+h]=l.data[h];g[d+
4]=a[d+4]}}d=0;for(j=a.length;d<j;d++)a[d]=g[d]||a[d];return b}}})})("psLib");
(function(k){window[k].module("config",function(){var n={"\u7070\u5ea6\u5904\u7406":"toGray","\u53cd\u8272":"toReverse","\u7070\u5ea6\u9608\u503c":"toThresh","\u9ad8\u65af\u6a21\u7cca":"gaussBlur","\u4eae\u5ea6":"alterRGB","\u6d6e\u96d5\u6548\u679c":"embossment","\u67e5\u627e\u8fb9\u7f18":"lapOfGauss","\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282":"setHSI","\u9a6c\u8d5b\u514b":"mosaic","\u6cb9\u753b":"oilPainting","\u8150\u8680":"corrode","\u9510\u5316":"sharp","\u6dfb\u52a0\u6742\u8272":"noise","\u66f2\u7ebf":"curve",
"\u6697\u89d2":"darkCorner"},b={"\u7f8e\u80a4":"e1","\u7d20\u63cf":"e2","\u81ea\u7136\u589e\u5f3a":"e3","\u7d2b\u8c03":"e4","\u67d4\u7126":"e5","\u590d\u53e4":"e6","\u9ed1\u767d":"e7","\u4efflomo":"e8","\u4eae\u767d\u589e\u5f3a":"e9","\u7070\u767d":"e10","\u7070\u8272":"e11","\u6696\u79cb":"e12","\u6728\u96d5":"e13"};return{getModuleName:function(a){return n[a]||a},getEasyFun:function(a){return b[a]||a}}})})("psLib");
(function(k){window[k].module("corrode",function(){return{process:function(n,b){for(var a=parseInt(b[0])||3,c=n.data,f=n.width,g=n.height,d=0;d<f;d++)for(var j=0;j<g;j++)for(var h=parseInt(2*Math.random()*a)-a,l=parseInt(2*Math.random()*a)-a,r=j*f+d,h=(j+h)*f+d+l,l=0;3>l;l++)c[4*r+l]=c[4*h+l];return n}}})})("psLib");
(function(k){window[k].module("curve",function(n){return{process:function(b,a){for(var c=n.lib.dorsyMath.lagrange(a[0],a[1]),f=b.data,g=b.width,d=b.height,j=0;j<g;j++)for(var h=0;h<d;h++)for(var l=h*g+j,r=0;3>r;r++)f[4*l+r]=c(f[4*l+r]);return b}}})})("psLib");
(function(k){window[k].module("darkCorner",function(n){return{process:function(b,a){for(var c=parseInt(a[0])||3,f=a[1]||30,g=b.data,d=b.width,j=b.height,h=2*d/3,l=1*j/2,r=n.lib.dorsyMath.distance([h,l]),c=r*(1-c/10),m=0;m<d;m++)for(var p=0;p<j;p++)for(var e=p*d+m,q=0;3>q;q++){var k;k=g[4*e+q];var s=(n.lib.dorsyMath.distance([m,p],[h,l])-c)/(r-c);0>s&&(s=0);k=(0*Math.pow(1-s,3)+0.06*s*Math.pow(1-s,2)+3*0.3*s*s*(1-s)+1*Math.pow(s,3))*k*f/255;g[4*e+q]-=k}return b}}})})("psLib");
(function(k){window[k].module("dorsyMath",function(n){var b={FFT1:function(a){function c(){g++;for(var h=f/Math.pow(2,g),j=f/h,n=0;n<h;n++)for(var m=n*j,k=(n+1)*j-1,e=g,q=Math.pow(2,e-1),v=0;m<=k-q;m++){var s=m+q,u=v*f/Math.pow(2,e),t=u+f/4;a[m]instanceof b.C||(a[m]=new b.C(a[m]));a[s]instanceof b.C||(a[s]=new b.C(a[s]));u=a[m].plus(a[s].mutiply(d[u]));t=a[m].plus(a[s].mutiply(d[t]));a[m]=u;a[s]=t;v++}1<h&&c()}for(var f=a.length,g=0,d=[],j=0;j<f;j++)d[j]=this.exp(-2*Math.PI*j/f);c();return a},DFT:function(){},
Matrix:function(a,c,b){var g=[];if(c){if(isNaN(c)){var d=/(\d+)\*/.exec(c)[1];c=/\*(\d+)/.exec(c)[1]}else d=c,c=b;if(a[0]&&a[0][0])for(b=0;b<d;b++){g[b]=[];for(var j=0;j<c;j++)g[b][j]=a[b][j]||0}else for(b=0;b<d;b++){g[b]=[];for(j=0;j<c;j++)g[b][j]=a[b*c+j]||0}this.m=d;this.n=c}else this.m=a.length,this.n=a[0].length;this.data=g},C:function(a,c){this.r=a||0;this.i=c||0},exp:function(a,c){a=a||0;c=c||1;var f=new b.C;f.r=c*Math.cos(a);f.i=c*Math.sin(a);return f},lagrange:function(a,c){var b=a.length;
return function(g){for(var d=0,j=0;j<b;j++){for(var h=1,l=1,n=0;n<b;n++)n!=j&&(h*=a[j]-a[n],l*=g-a[n]);d+=c[j]*(l/h)}return d}},applyMatrix:function(a,c,f){f=f||0;var g=a.data,d=a.width,j=c.length;c=new b.Matrix(c,j,1);for(var h=[],l=-(Math.sqrt(j)-1)/2,k=0,m=g.length;k<m;k+=4){var p=k/4,e=parseInt(p/d),q=p%d;if(!(0==e||0==q)){for(var v=[[],[],[]],s=l;s<=-l;s++)for(var u=e+s,t=l;t<=-l;t++)for(var w=4*(u*d+(q+t)),p=0;3>p;p++)v[p].push(g[w+p]);e=(new n.lib.dorsyMath.Matrix(v,3,j)).mutiply(c);for(p=
0;3>p;p++)h[k+p]=e.data[p];h[k+4]=g[k+4]}}k=0;for(m=g.length;k<m;k++)h[k]&&(g[k]=h[k]<f?h[k]:g[k]);return a},RGBToHSI:function(a,c,b){var g=(a-c+a-b)/2/Math.sqrt((a-c)*(a-c)+(a-b)*(c-b))||0,g=Math.acos(g),g=b>c?2*Math.PI-g:g,d=1-3*Math.min(a,c,b)/(a+c+b);g>2*Math.PI&&(g=2*Math.PI);0>g&&(g=0);return{H:g,S:d,I:(a+c+b)/3}},HSIToRGB:function(a,b,f){0>a?(a%=2*Math.PI,a+=2*Math.PI):a%=2*Math.PI;if(a<=2*Math.PI/3)var g=f*(1-b),d=f*(1+b*Math.cos(a)/Math.cos(Math.PI/3-a)),j=3*f-(d+g);else a<=4*Math.PI/3?(a-=
2*Math.PI/3,d=f*(1-b),j=f*(1+b*Math.cos(a)/Math.cos(Math.PI/3-a)),g=3*f-(j+d)):(a-=4*Math.PI/3,j=f*(1-b),g=f*(1+b*Math.cos(a)/Math.cos(Math.PI/3-a)),d=3*f-(j+g));return{R:d,G:j,B:g}},applyInHSI:function(a,b){for(var f=a.data,g=0,d=f.length;g<d;g+=4){var j=this.RGBToHSI(f[g],f[g+1],f[g+2]);b(j);1<j.S&&(j.S=1);0>j.S&&(j.S=0);j=this.HSIToRGB(j.H,j.S,j.I);f[g]=j.R;f[g+1]=j.G;f[g+2]=j.B}},applyInCoordinate:function(){},distance:function(a,c){c=c||[0,0];a=new b.C(a[0],a[1]);c=new b.C(c[0],c[1]);return a.minus(c).distance()}};
b.Matrix.prototype={plus:function(a){if(this.m!=a.m||this.n!=a.n)throw Error("\u77e9\u9635\u52a0\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,this.n),f=0;f<this.m;f++)for(var g=0;g<this.n;g++)c.data[f][g]=this.data[f][g]+a.data[f][g];return c},minus:function(a){if(this.m!=a.m||this.n!=a.n)throw Error("\u77e9\u9635\u51cf\u6cd5\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,this.n),f=0;f<this.m;f++)for(var g=0;g<this.n;g++)c.data[f][g]=this.data[f][g]-
a.data[f][g];return c},mutiply:function(a){if(this.n!=a.m)throw Error("\u77e9\u9635\u4e58\u6cd5\u884c\u5217\u4e0d\u5339\u914d");for(var c=new b.Matrix([],this.m,a.n),f=0;f<this.m;f++)for(var g=0;g<a.n;g++){for(var d=0,j=0;j<this.n;j++)d+=this.data[f][j]*a.data[j][g];c.data[f][g]=d}return c}};b.C.prototype={plus:function(a){var c=new b.C;c.r=this.r+a.r;c.i=this.i+a.i;return c},minus:function(a){var c=new b.C;c.r=this.r-a.r;c.i=this.i-a.i;return c},mutiply:function(a){var c=new b.C;c.r=this.r*a.r-this.i*
a.i;c.i=this.r*a.i+this.i*a.r;return c},divide:function(a){var c=new b.C,f=a.mutiply(a.conjugated());a=this.mutiply(a.conjugated());c.r=a.r/f.r;c.i=a.i/f.r;return c},conjugated:function(){return new b.C(this.r,-this.i)},distance:function(){return Math.sqrt(this.r*this.r+this.i*this.i)}};return b})})("psLib");
(function(k){window[k].module("easy",function(){return{getFun:function(n){return{e1:function(){return this.clone().add(this.act("\u9ad8\u65af\u6a21\u7cca",10),"\u6ee4\u8272").act("\u4eae\u5ea6",-10,5)},e2:function(){var b=this.act("\u7070\u5ea6\u5904\u7406").clone();return this.add(b.act("\u53cd\u8272").act("\u9ad8\u65af\u6a21\u7cca",8),"\u989c\u8272\u51cf\u6de1").act("\u9510\u5316",1)},e3:function(){return this.act("\u66f2\u7ebf",[0,190,255],[0,229,255])},e4:function(){var b=this.clone();return this.add(b.act("\u9ad8\u65af\u6a21\u7cca",
3),"\u6b63\u7247\u53e0\u5e95","RG")},e5:function(){var b=this.clone();return this.add(b.act("\u9ad8\u65af\u6a21\u7cca",6),"\u53d8\u6697")},e6:function(){this.clone();return this.act("\u7070\u5ea6\u5904\u7406").add(window[k](this.canvas.width,this.canvas.height,"#808080").act("\u6dfb\u52a0\u6742\u8272").act("\u9ad8\u65af\u6a21\u7cca",4).act("\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282",32,19,0,!0),"\u53e0\u52a0")},e7:function(){return this.act("\u7070\u5ea6\u5904\u7406")},e8:function(){return this.clone().add(this.clone(),
"\u6ee4\u8272").add(this.clone(),"\u67d4\u5149").add(this.clone().act("\u53cd\u8272"),"\u6b63\u5e38","20%","B").act("\u6697\u89d2",6,200)},e9:function(){return this.clone().add(this.clone().act("\u66f2\u7ebf",[0,50,255],[0,234,255]),"\u67d4\u5149")},e10:function(){return this.act("\u7070\u5ea6\u5904\u7406").act("\u66f2\u7ebf",[0,61,69,212,255],[0,111,176,237,255])},e11:function(){return this.act("\u7070\u5ea6\u5904\u7406").act("\u66f2\u7ebf",[0,60,142,194,255],[0,194,240,247,255])},e12:function(){var b=
this.clone().act("\u8272\u76f8/\u9971\u548c\u5ea6\u8c03\u8282",36,47,8,!0).act("\u6697\u89d2",6,150);return this.add(b,"\u53e0\u52a0")},e13:function(){var b=this.clone().act("\u9a6c\u8d5b\u514b").act("\u67e5\u627e\u8fb9\u7f18").act("\u6d6e\u96d5\u6548\u679c");return this.add(b,"\u7ebf\u6027\u5149")}}[n]}}})})("psLib");
(function(k){window[k].module("embossment",function(){return{process:function(n){for(var b=n.data,a=n.width,c=[],f=0,g=b.length;f<g;f+=4){var d=f/4,j=parseInt(d/a),h=d%a,d=4*((j-1)*a+(h-1)),l=4*(j+1)*a+4*(h+1);if(!(0==j||0==h)){for(j=0;3>j;j++)c[f+j]=b[d+j]-b[l+j]+127.5;c[f+4]=b[f+4]}}f=0;for(g=b.length;f<g;f++)b[f]=c[f]||b[f];return n}}})})("psLib");
(function(k){window[k].module("gaussBlur",function(){return{process:function(n,b,a){var c=n.data,f=n.width,g=n.height,d=[],j=0,h,l,k,m,p,e;b=Math.floor(b)||3;a=a||b/3;h=1/(Math.sqrt(2*Math.PI)*a);m=-1/(2*a*a);p=0;for(a=-b;a<=b;a++,p++)k=h*Math.exp(m*a*a),d[p]=k,j+=k;p=0;for(a=d.length;p<a;p++)d[p]/=j;for(h=0;h<g;h++)for(a=0;a<f;a++){j=l=k=m=0;for(e=-b;e<=b;e++)p=a+e,0<=p&&p<f&&(p=4*(h*f+p),l+=c[p]*d[e+b],k+=c[p+1]*d[e+b],m+=c[p+2]*d[e+b],j+=d[e+b]);p=4*(h*f+a);c[p]=l/j;c[p+1]=k/j;c[p+2]=m/j}for(a=
0;a<f;a++)for(h=0;h<g;h++){j=l=k=m=0;for(e=-b;e<=b;e++)p=h+e,0<=p&&p<g&&(p=4*(p*f+a),l+=c[p]*d[e+b],k+=c[p+1]*d[e+b],m+=c[p+2]*d[e+b],j+=d[e+b]);p=4*(h*f+a);c[p]=l/j;c[p+1]=k/j;c[p+2]=m/j}n.data=c;return n}}})})("psLib");(function(k){window[k].module("lapOfGauss",function(n){return{process:function(b){return n.lib.dorsyMath.applyMatrix(b,[0,1,0,1,-4,1,0,1,0],250)}}})})("psLib");
(function(k){window[k].module("mosaic",function(){return{process:function(n,b){for(var a=parseInt(b[0])||3,c=n.data,f=n.width,g=n.height,a=2*a+1,d=0,j=parseInt(f/a);d<j;d++)for(var h=0,l=parseInt(g/a);h<l;h++){for(var k=[],m=[0,0,0],p=0;p<a;p++)for(var e=0;e<a;e++){var q=(h*a+p)*f+d*a+e;m[0]+=c[4*q];m[1]+=c[4*q+1];m[2]+=c[4*q+2]}k[0]=m[0]/(a*a);k[1]=m[1]/(a*a);k[2]=m[2]/(a*a);for(p=0;p<a;p++)for(e=0;e<a;e++)q=(h*a+p)*f+d*a+e,c[4*q]=k[0],c[4*q+1]=k[1],c[4*q+2]=k[2]}return n}}})})("psLib");
(function(k){window[k].module("noise",function(){return{process:function(k,b){for(var a=parseInt(b[0])||100,c=k.data,f=k.width,g=k.height,d=0;d<f;d++)for(var j=0;j<g;j++)for(var h=j*f+d,l=0;3>l;l++){var r=parseInt(2*Math.random()*a)-a;c[4*h+l]+=r}return k}}})})("psLib");
(function(k){window[k].module("oilPainting",function(){return{process:function(k,b){for(var a=parseInt(b[0])||16,c=k.data,f=k.width,g=k.height,d=0;d<f;d++)for(var j=0;j<g;j++){for(var h=j*f+d,l=0,r=0;3>r;r++)l+=c[4*h+r];l/=3;l=parseInt(l/a)*a;for(r=0;3>r;r++)c[4*h+r]=l}return k}}})})("psLib");
(function(k){window[k].module("setHSI",function(k){return{process:function(b,a){a[0]=a[0]/180*Math.PI;a[1]=a[1]/100||0;a[2]=255*(a[2]/100)||0;a[3]=a[3]||!1;k.lib.dorsyMath.applyInHSI(b,function(b){a[3]?(b.H=a[0],b.S=a[1]):(b.H+=a[0],b.S+=a[1]);b.I+=a[2]});return b}}})})("psLib");
(function(k){window[k].module("sharp",function(){return{process:function(k,b){for(var a=b[0]||0.6,c=k.data,f=k.width,g=0,d=c.length;g<d;g+=4){var j=g/4,h=parseInt(j/f),l=j%f;if(!(0==h||0==l))for(var r=4*((h-1)*f+(l-1)),h=4*((h-1)*f+l),j=4*(j-1),l=0;3>l;l++)c[g+l]+=(c[g+l]-(c[h+l]+c[j+l]+c[r+l])/3)*a}return k}}})})("psLib");
(function(k){window[k].module("toGray",function(){return{process:function(k){for(var b=k.data,a=0,c=b.length;a<c;a+=4){var f=parseInt((b[a]+b[a+1]+b[a+2])/3);b[a+2]=b[a+1]=b[a]=f}k.data=b;return k}}})})("psLib");(function(k){window[k].module("toReverse",function(){return{process:function(k){for(var b=k.data,a=0,c=b.length;a<c;a+=4)b[a]=255-b[a],b[a+1]=255-b[a+1],b[a+2]=255-b[a+2];k.data=b;return k}}})})("psLib");
(function(k){window[k].module("toThresh",function(k){return{process:function(b,a){b=k.lib.toGray.process(b);var c=b.data;a=a[0]||128;for(var f=0,g=c.length;f<g;f++)(f+1)%4&&(c[f]=c[f]>a?255:0);b.data=c;return b}}})})("psLib");